# kill the docker service of the target node
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: engine-nginx
  namespace: litmus
spec:
  engineState: "active"
  annotationCheck: "false"
  chaosServiceAccount: docker-service-kill-sa
  experiments:
  - name: docker-service-kill
    spec:
      components:
        env:
        # name of the target node
        - name: NODE_LABEL
          value: 'nodegroup-role=web-workload' 
        - name: TOTAL_CHAOS_DURATION
          VALUE: '900'
