---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-debug
  labels:
    name: user
  namespace: sock-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: user
  template:
    metadata:
      labels:
        name: user
    spec:
      shareProcessNamespace: true
      containers:
        - name: user
          image: public.ecr.aws/j8e3t3x0/user:0.4.7
          resources:
            limits:
              cpu: 300m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 80
          env:
            - name: mongo
              value: user-db:27017
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            capabilities:
              drop:
                - all
              add:
                - NET_BIND_SERVICE
            readOnlyRootFilesystem: true
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 300
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 180
            periodSeconds: 3
        - name: debug
          image: public.ecr.aws/j8e3t3x0/netshoot:latest
          command: ["/bin/bash", "-c", "--"]
          args: ["while true; do sleep 30; done;"]
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
          stdin: true
          tty: true
      nodeSelector:
        beta.kubernetes.io/os: linux
